//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34209
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;
using FATEC.ArcadeSpaceBattle.Abstractions;

namespace FATEC.ArcadeSpaceBattle.Controllers {
	public class ShootController {

		protected IInputProvider input;
		protected float fireRate;
		protected GameObject laser;
		protected Transform ship;
		protected MonoBehaviour script;

		public ShootController ( IInputProvider input,
		                        float fireRate,
		                        GameObject laser,
		                        Transform ship,
		                        MonoBehaviour script){
			this.input = input;
			this.fireRate = fireRate;
			this.laser = laser;
			this.ship = ship;
			this.script = script;
			script.StartCoroutine (Updater ());
		}

		private IEnumerator Updater () {
			while (true) {
				if (input.GetButton(0)) 
					GameObject.Instantiate ( this.laser, ship.position, ship.rotation); 
				yield return new WaitForSeconds( this.fireRate);
			}
		}
	}
}

